apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-app-release
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: chart
      sourceRef:
        kind: GitRepository
        name: myappgitsource
        namespace: default
      interval: 1m
  values:
    deployment:
      name: redis
      version: 3630
      replicas: 2
      image: redis
      port: 8080